version: "3"

tasks:
  run:
    dir: ./services/service
    cmds:
      - go run ./main.go
  swag:
    dir: ./services/service
    generates:
      - docs/swagger.json
      - docs/swagger.yaml
      - docs/docs.go
    cmds:
      - swag init --parseDependency --parseInternal --output ./docs