host: 127.0.0.1:3001
info:
  contact: {}
  title: <Service>
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    description: Bearer Token Authortization
    in: Header
    name: Authorization
    type: apiKey
swagger: "2.0"
